import Foundation

enum L10n {
    private static var isTurkish: Bool {
        if let preferred = Bundle.main.preferredLocalizations.first?.lowercased() {
            return preferred.hasPrefix("tr")
        }
        return Locale.preferredLanguages.first?.lowercased().hasPrefix("tr") ?? false
    }

    private static var locale: Locale {
        isTurkish ? Locale(identifier: "tr_TR") : Locale(identifier: "en_US")
    }

    static func string(_ key: String, _ arguments: CVarArg...) -> String {
        let format = (isTurkish ? tr : en)[key] ?? en[key] ?? key
        guard !arguments.isEmpty else { return format }
        return String(format: format, locale: locale, arguments: arguments)
    }

    private static let en: [String: String] = [
        "app.name": "StoryComicAI",
        "tab.home": "Home",
        "tab.library": "Library",
        "tab.settings": "Settings",
        "action.continue": "Continue",
        "action.next": "Next",
        "action.get_started": "Get Started",
        "action.try_again": "Try Again",
        "action.sign_out": "Sign Out",
        "action.enter_studio": "Enter Studio",
        "action.add_demo_photo": "Add Demo Photo",
        "action.use_fixture": "Use Fixture",
        "action.upload_continue": "Upload and Continue",
        "action.generate_comic": "Generate Comic",
        "action.continue_reveal": "Continue to reveal",
        "action.rendering_comic": "Rendering comic",
        "action.continue_generation": "Continue to Generation",
        "action.turn_story_into_comic": "Turn this into a comic",
        "action.approve_character_soon": "Approve Character (Soon)",
        "common.story": "Story",
        "common.scenes": "Scenes",
        "common.panels": "Panels",
        "common.comic": "Comic",
        "common.selected": "Selected",
        "common.tap_to_choose": "Tap to choose",
        "common.status": "Status",
        "common.stage": "Stage",
        "common.front": "Front",
        "common.three_quarter": "3/4",
        "common.side": "Side",
        "home.brand": "StoryComicAI",
        "home.title": "Your personal comic studio",
        "home.subtitle": "Turn your photos and story into a calm, premium comic edition you can open like a finished book.",
        "home.start_title": "Start a new edition",
        "home.start_body": "Upload photos, write the story, choose a visual edition and reveal the finished comic like a bound book.",
        "home.create_cta": "Create your comic",
        "home.hero_cover_title": "Personal Edition",
        "home.hero_cover_subtitle": "Bound for one",
        "home.hero_cover_eyebrow": "Edition",
        "home.loading_title": "Loading your collection",
        "home.loading_subtitle": "Gathering recent editions",
        "home.error_title": "Could not load collection",
        "home.recent_title": "Recent Editions",
        "home.recent_subtitle": "Return to the books already on your desk.",
        "home.empty_title": "Your shelf is empty",
        "home.empty_body": "Create your first personalized comic and it will appear here as a finished edition.",
        "create.eyebrow": "Edition Setup",
        "create.title": "Name your comic",
        "create.subtitle": "Give this edition a strong title before you build the story world around it.",
        "create.field": "Project Name",
        "create.placeholder": "Example: Shadow of Istanbul",
        "create.help": "This title becomes the cover headline of the comic book edition.",
        "create.nav": "Create Project",
        "create.validation.short": "Project title must be at least 3 characters.",
        "story.eyebrow": "Story Source",
        "story.title": "Tell the story",
        "story.subtitle": "Write the actual story you want turned into a comic book. We use this text to shape scenes, captions, dialogue beats and page flow.",
        "story.field": "Your Story",
        "story.help": "Write events, conflict, emotional turns and key moments. This text becomes the comic's narrative backbone.",
        "photo.eyebrow": "Hero Source",
        "photo.title": "Choose reference photos",
        "photo.subtitle": "These images define the face and identity that should persist across the comic.",
        "photo.uploaded": "Uploaded Photos",
        "photo.empty": "No photos selected yet.",
        "photo.nav": "Photo Upload",
        "photo.error.project_missing": "Project is missing.",
        "photo.error.add_photo": "Please add at least one photo.",
        "action.back": "Back",
        "style.nav": "Style",
        "style.header_title": "Choose the edition",
        "style.header_subtitle": "Each style changes the cover language, page tone and final collectible feel of your comic.",
        "style.error.not_ready_title": "Generation Not Ready",
        "style.error.not_ready_message": "Project could not be prepared for generation. Please retry.",
        "style.error.title_missing": "Project title is missing. Go back and set a valid title.",
        "style.selected_for_rendering": "Selected for rendering",
        "generation.nav": "Generation",
        "generation.title": "Building your preview edition",
        "generation.subtitle": "We are planning the first pages, laying out the panels and preparing the book reveal.",
        "generation.preview_panels": "Preview panels",
        "generation.scene_breakdown": "Scene breakdown",
        "generation.rendered_pages": "Rendered pages",
        "generation.rendered_pages_preparing": "Preparing the first comic pages.",
        "generation.page_summary": "Page %d • %@",
        "generation.preparing_page_summary": "Preparing page %d • %@",
        "generation.error_failed": "Comic generation failed.",
        "generation.not_ready_title": "Generation Not Ready",
        "generation.not_ready_message": "Project could not be prepared for generation. Please retry.",
        "generation.stage.queued": "Queued",
        "generation.stage.story_planner": "Story planner",
        "generation.stage.character_bible": "Character bible",
        "generation.stage.style_guide": "Style guide",
        "generation.stage.reference_taxonomy": "Reference taxonomy",
        "generation.stage.panel_prompts": "Panel prompts",
        "generation.stage.page_composer": "Page composer",
        "generation.stage.completed": "Completed",
        "generation.stage.failed": "Failed",
        "generation.step.story_planner": "Story planner",
        "generation.step.character_bible": "Character bible",
        "generation.step.style_guide": "Style guide",
        "generation.step.reference_taxonomy": "Reference taxonomy",
        "generation.step.panel_prompts": "Panel prompts",
        "generation.step.page_composer": "Page composer",
        "generation.step.story_planner_beats": "Story planner (%d beats)",
        "generation.step.character_bible_codename": "Character bible (%@)",
        "generation.step.style_guide_label": "Style guide (%@)",
        "generation.step.reference_taxonomy_count": "Reference taxonomy (%d)",
        "generation.step.panel_prompts_count": "Panel prompts (%d)",
        "generation.step.page_composer_count": "Page composer (%d pages)",
        "library.loading_title": "Loading your shelf",
        "library.loading_subtitle": "Arranging your finished editions",
        "library.error_title": "Failed to load library",
        "library.eyebrow": "Collection",
        "library.title": "Your Comic Shelf",
        "library.subtitle_empty": "Your collection is waiting for its first edition.",
        "library.subtitle_count": "%d comic editions in your collection",
        "library.empty_title": "Your first comic belongs here",
        "library.empty_body": "Once a project is generated, its finished edition will appear on this shelf.",
        "settings.title": "Settings",
        "settings.subtitle": "Account and product preferences for your comic studio.",
        "settings.session": "Session",
        "settings.signed_in": "Signed In",
        "settings.signed_out": "Signed Out",
        "settings.ready": "Your comic studio remains ready on this device.",
        "signin.eyebrow": "Personal Comic Studio",
        "signin.title": "StoryComicAI",
        "signin.subtitle": "Create a premium comic edition where you are the main character, then open it like a finished book.",
        "signin.cover_title": "Your Story,\nBound As A Book",
        "signin.cover_subtitle": "Hero preview, premium reveal and export-ready pages.",
        "signin.cover_eyebrow": "Prestige Edition",
        "signin.cover_badge": "Made For You",
        "signin.section_title": "Developer Sign In",
        "signin.section_subtitle": "Use a local Apple token handoff to enter the live comic flow.",
        "signin.token_label": "Apple Identity Token",
        "signin.token_placeholder": "identity token",
        "hero.nav": "Hero Preview",
        "hero.loading_title": "Generating Hero Preview",
        "hero.loading_subtitle": "This can take a few moments.",
        "hero.failed_title": "Hero Preview Failed",
        "hero.error.project_not_ready": "Project is not ready.",
        "hero.error.upload_first": "Upload photos before starting hero preview.",
        "hero.status_prefix": "Status: %@",
        "hero.stage_prefix": "Stage: %@",
        "hero.preview_section": "Preview angles",
        "loading.default_title": "Loading",
        "loading.preparing_studio": "Preparing your comic studio",
        "error.default_title": "Something went wrong",
        "error.default_message": "Please try again.",
        "settings.nav": "Settings",
        "onboarding.headline": "A comic book app,\nnot an AI tool.",
        "onboarding.page1.title": "Turn Yourself Into the Hero",
        "onboarding.page1.subtitle": "Upload photos and build a personal comic with consistent character identity.",
        "onboarding.page2.title": "Structured Story Pipeline",
        "onboarding.page2.subtitle": "Scenes and panels are generated in sequence for a coherent reading flow.",
        "onboarding.page3.title": "Premium Comic Experience",
        "onboarding.page3.subtitle": "Cover pages, polished typography, and smooth page-by-page storytelling.",
        "api.invalid_url": "Invalid server URL.",
        "api.invalid_response": "Server response was invalid.",
        "api.unauthorized": "Your session is not authorized.",
        "api.transport": "Network error: %@",
        "api.server": "Server error occurred. Please try again.",
        "api.decoding": "Could not process server response.",
        "api.empty_response": "Server returned empty data.",
        "project.status.complete": "Complete",
        "project.status.preview_ready": "Preview Ready",
        "project.status.hero_ready": "Hero Ready",
        "project.status.in_production": "In Production",
        "project.unlock.unlocked": "Unlocked",
        "project.unlock.preview": "Preview",
        "project.collection_subtitle": "%@ | %@",
        "style.manga.name": "Manga",
        "style.western.name": "Western Comic",
        "style.cartoon.name": "Cartoon",
        "style.cinematic.name": "Cinematic",
        "style.childrens.name": "Children's Book",
        "style.manga.blurb": "Ink-forward, dramatic framing and high-contrast momentum.",
        "style.western.blurb": "Vintage pulp energy with bold color and collector-print charm.",
        "style.cartoon.blurb": "Stylized character acting with playful shapes and clean rhythm.",
        "style.cinematic.blurb": "Prestige-cover storytelling with dramatic light and polished pacing.",
        "style.childrens.blurb": "Warm storybook softness built for giftable keepsake moments.",
        "style.manga.mood": "Ink Edition",
        "style.western.mood": "Collector Issue",
        "style.cartoon.mood": "Animated Edition",
        "style.cinematic.mood": "Prestige Edition",
        "style.childrens.mood": "Storybook Edition",
        "style.manga.signature": "High-contrast speed lines and ink-forward drama.",
        "style.western.signature": "Vintage pulp color with bold collector energy.",
        "style.cartoon.signature": "Expressive shapes and clean animated rhythm.",
        "style.cinematic.signature": "Prestige framing, dramatic light and premium pacing.",
        "style.childrens.signature": "Warm storybook softness for giftable keepsakes.",
        "style.manga.cover_title": "Manga",
        "style.western.cover_title": "Western",
        "style.cartoon.cover_title": "Cartoon",
        "style.cinematic.cover_title": "Cinema",
        "style.childrens.cover_title": "Storybook",
        "style.manga.cover_subtitle": "Ink drama",
        "style.western.cover_subtitle": "Collector pulp",
        "style.cartoon.cover_subtitle": "Clean shapes",
        "style.cinematic.cover_subtitle": "Prestige pace",
        "style.childrens.cover_subtitle": "Warm keepsake",
        "style.manga.cover_eyebrow": "Ink",
        "style.western.cover_eyebrow": "Issue",
        "style.cartoon.cover_eyebrow": "Edition",
        "style.cinematic.cover_eyebrow": "Prestige",
        "style.childrens.cover_eyebrow": "Story",
        "step.pending": "Pending",
        "step.active": "In Progress",
        "step.completed": "Done",
        "step.failed": "Failed",
        "hero_status.queued": "Queued",
        "hero_status.running": "Running",
        "hero_status.succeeded": "Succeeded",
        "hero_status.failed": "Failed"
    ]

    private static let tr: [String: String] = [
        "app.name": "StoryComicAI",
        "tab.home": "Ana Sayfa",
        "tab.library": "Koleksiyon",
        "tab.settings": "Ayarlar",
        "action.continue": "Devam Et",
        "action.next": "İleri",
        "action.get_started": "Başlayın",
        "action.try_again": "Tekrar Dene",
        "action.sign_out": "Çıkış Yap",
        "action.enter_studio": "Stüdyoya Gir",
        "action.add_demo_photo": "Demo Foto Ekle",
        "action.use_fixture": "Örnek Görsel Kullan",
        "action.upload_continue": "Yükle ve Devam Et",
        "action.generate_comic": "Çizgi Romanını Hazırla",
        "action.continue_reveal": "Kitabı Aç",
        "action.rendering_comic": "Çizgi Roman Hazırlanıyor",
        "action.continue_generation": "Üretime Devam Et",
        "action.turn_story_into_comic": "Görsel sürüme geç",
        "action.approve_character_soon": "Karakteri Onayla (Yakında)",
        "common.story": "Hikâye",
        "common.scenes": "Sahneler",
        "common.panels": "Paneller",
        "common.comic": "Çizgi Roman",
        "common.selected": "Seçildi",
        "common.tap_to_choose": "Dokunarak seç",
        "common.status": "Durum",
        "common.stage": "Aşama",
        "common.front": "Ön",
        "common.three_quarter": "3/4",
        "common.side": "Yan",
        "home.brand": "StoryComicAI",
        "home.title": "Kişisel çizgi roman stüdyon",
        "home.subtitle": "Fotoğraflarını ve hikâyeni sakin, premium bir çizgi roman sürümüne dönüştür; sonra tamamlanmış bir kitap gibi aç.",
        "home.start_title": "Yeni bir sürüm hazırla",
        "home.start_body": "Fotoğrafları yükle, hikâyeni yaz, görsel sürümü seç ve tamamlanan çizgi romanını ciltli bir kitap gibi ortaya çıkar.",
        "home.create_cta": "Çizgi romanını hazırla",
        "home.hero_cover_title": "Kişisel Sürüm",
        "home.hero_cover_subtitle": "Sana özel cilt",
        "home.hero_cover_eyebrow": "Sürüm",
        "home.loading_title": "Koleksiyonun yükleniyor",
        "home.loading_subtitle": "Son sürümler hazırlanıyor",
        "home.error_title": "Koleksiyon yüklenemedi",
        "home.recent_title": "Son Sürümler",
        "home.recent_subtitle": "Masandaki kitaplara geri dön.",
        "home.empty_title": "Rafın şu an boş",
        "home.empty_body": "İlk kişisel çizgi romanını hazırladığında tamamlanan sürüm burada görünecek.",
        "create.eyebrow": "Sürüm ayarı",
        "create.title": "Çizgi romanını adlandır",
        "create.subtitle": "Hikâye dünyasını kurmadan önce bu sürüme güçlü bir başlık ver.",
        "create.field": "Proje adı",
        "create.placeholder": "Örnek: İstanbul'un Gölgesi",
        "create.help": "Bu başlık çizgi roman sürümünün kapak başlığı olur.",
        "create.nav": "Proje Oluştur",
        "create.validation.short": "Proje başlığı en az 3 karakter olmalı.",
        "story.eyebrow": "Hikâye kaynağı",
        "story.title": "Hikâyeni yaz",
        "story.subtitle": "Çizgi romana dönüşmesini istediğin gerçek hikâyeyi yaz. Bu metin sahneleri, altyazıları, diyalog ritmini ve sayfa akışını belirler.",
        "story.field": "Hikâyen",
        "story.help": "Olayları, çatışmayı, duygusal kırılmaları ve kilit anları yaz. Bu metin çizgi romanın anlatı omurgasına dönüşür.",
        "photo.eyebrow": "Karakter kaynağı",
        "photo.title": "Referans fotoğrafları seç",
        "photo.subtitle": "Bu görseller çizgi roman boyunca korunacak yüzü ve kimliği belirler.",
        "photo.uploaded": "Yüklenen fotoğraflar",
        "photo.empty": "Henüz fotoğraf seçilmedi.",
        "photo.nav": "Fotoğraf Yükleme",
        "photo.error.project_missing": "Proje bulunamadı.",
        "photo.error.add_photo": "Lütfen en az bir fotoğraf ekle.",
        "action.back": "Geri",
        "style.nav": "Görsel Sürüm",
        "style.header_title": "Görsel sürümü seç",
        "style.header_subtitle": "Her stil, kapağın dilini, sayfa tonunu ve çizgi romanının koleksiyon hissini değiştirir.",
        "style.error.not_ready_title": "Üretim hazır değil",
        "style.error.not_ready_message": "Proje üretime hazırlanamadı. Lütfen yeniden dene.",
        "style.error.title_missing": "Proje başlığı eksik. Geri dönüp geçerli bir başlık belirle.",
        "style.selected_for_rendering": "Render için seçildi",
        "generation.nav": "Hazırlanıyor",
        "generation.title": "Ön izleme sürümün hazırlanıyor",
        "generation.subtitle": "İlk sayfaları planlıyor, panelleri yerleştiriyor ve kitabın ortaya çıkışını hazırlıyoruz.",
        "generation.preview_panels": "Ön izleme panelleri",
        "generation.scene_breakdown": "Sahne planı",
        "generation.rendered_pages": "Hazırlanan sayfalar",
        "generation.rendered_pages_preparing": "İlk çizgi roman sayfaları hazırlanıyor.",
        "generation.page_summary": "Sayfa %d • %@",
        "generation.preparing_page_summary": "Sayfa hazırlanıyor %d • %@",
        "generation.error_failed": "Çizgi roman hazırlanamadı.",
        "generation.not_ready_title": "Üretim hazır değil",
        "generation.not_ready_message": "Proje üretime hazırlanamadı. Lütfen yeniden dene.",
        "generation.stage.queued": "Sırada",
        "generation.stage.story_planner": "Hikâye planlayıcı",
        "generation.stage.character_bible": "Karakter kimliği",
        "generation.stage.style_guide": "Stil kılavuzu",
        "generation.stage.reference_taxonomy": "Referans sınıflandırması",
        "generation.stage.panel_prompts": "Panel talimatları",
        "generation.stage.page_composer": "Sayfa kurgusu",
        "generation.stage.completed": "Tamamlandı",
        "generation.stage.failed": "Başarısız",
        "generation.step.story_planner": "Hikâye planlayıcı",
        "generation.step.character_bible": "Karakter kimliği",
        "generation.step.style_guide": "Stil kılavuzu",
        "generation.step.reference_taxonomy": "Referans sınıflandırması",
        "generation.step.panel_prompts": "Panel talimatları",
        "generation.step.page_composer": "Sayfa kurgusu",
        "generation.step.story_planner_beats": "Hikâye planlayıcı (%d beat)",
        "generation.step.character_bible_codename": "Karakter kimliği (%@)",
        "generation.step.style_guide_label": "Stil kılavuzu (%@)",
        "generation.step.reference_taxonomy_count": "Referans sınıflandırması (%d)",
        "generation.step.panel_prompts_count": "Panel talimatları (%d)",
        "generation.step.page_composer_count": "Sayfa kurgusu (%d sayfa)",
        "library.loading_title": "Rafın yükleniyor",
        "library.loading_subtitle": "Tamamlanan sürümler diziliyor",
        "library.error_title": "Koleksiyon yüklenemedi",
        "library.eyebrow": "Koleksiyon",
        "library.title": "Çizgi Roman Rafın",
        "library.subtitle_empty": "Koleksiyonun ilk sürümünü bekliyor.",
        "library.subtitle_count": "Koleksiyonunda %d çizgi roman sürümü var",
        "library.empty_title": "İlk çizgi romanın burada yer alacak",
        "library.empty_body": "Bir proje hazırlandığında tamamlanan sürümü bu rafta görünür.",
        "settings.title": "Ayarlar",
        "settings.subtitle": "Çizgi roman stüdyon için hesap ve ürün tercihleri.",
        "settings.session": "Oturum",
        "settings.signed_in": "Oturum Açık",
        "settings.signed_out": "Oturum Kapalı",
        "settings.ready": "Çizgi roman stüdyon bu cihazda hazır.",
        "signin.eyebrow": "Kişisel Çizgi Roman Stüdyosu",
        "signin.title": "StoryComicAI",
        "signin.subtitle": "Başrolde senin olduğun premium bir çizgi roman sürümü oluştur, sonra onu tamamlanmış bir kitap gibi aç.",
        "signin.cover_title": "Hikâyen,\nKitap Olsun",
        "signin.cover_subtitle": "Karakter ön izlemesi, premium reveal ve dışa aktarmaya hazır sayfalar.",
        "signin.cover_eyebrow": "Özel Sürüm",
        "signin.cover_badge": "Senin İçin",
        "signin.section_title": "Geliştirici Girişi",
        "signin.section_subtitle": "Canlı çizgi roman akışına girmek için yerel Apple token aktarımını kullan.",
        "signin.token_label": "Apple kimlik belirteci",
        "signin.token_placeholder": "kimlik belirteci",
        "hero.nav": "Karakter Ön İzleme",
        "hero.loading_title": "Karakter ön izlemesi hazırlanıyor",
        "hero.loading_subtitle": "Bu işlem kısa bir süre alabilir.",
        "hero.failed_title": "Karakter ön izlemesi başarısız oldu",
        "hero.error.project_not_ready": "Proje henüz hazır değil.",
        "hero.error.upload_first": "Karakter ön izlemesini başlatmadan önce fotoğraf yükle.",
        "hero.status_prefix": "Durum: %@",
        "hero.stage_prefix": "Aşama: %@",
        "hero.preview_section": "Ön izleme açıları",
        "loading.default_title": "Yükleniyor",
        "loading.preparing_studio": "Çizgi roman stüdyon hazırlanıyor",
        "error.default_title": "Bir sorun oluştu",
        "error.default_message": "Lütfen yeniden dene.",
        "settings.nav": "Ayarlar",
        "onboarding.headline": "Bir yapay zekâ aracı değil,\nbir çizgi roman ürünü.",
        "onboarding.page1.title": "Kendini kahramana dönüştür",
        "onboarding.page1.subtitle": "Fotoğraflarını yükle ve tutarlı karakter kimliğiyle kişisel bir çizgi roman hazırla.",
        "onboarding.page2.title": "Yapılandırılmış hikâye akışı",
        "onboarding.page2.subtitle": "Sahneler ve paneller, tutarlı bir okuma akışı için sıralı biçimde oluşturulur.",
        "onboarding.page3.title": "Premium çizgi roman deneyimi",
        "onboarding.page3.subtitle": "Kapak sayfaları, özenli tipografi ve sayfa sayfa akıcı anlatım.",
        "api.invalid_url": "Sunucu adresi geçersiz.",
        "api.invalid_response": "Sunucu yanıtı geçersiz.",
        "api.unauthorized": "Oturumun yetkili değil.",
        "api.transport": "Ağ hatası: %@",
        "api.server": "Sunucu hatası oluştu. Lütfen yeniden dene.",
        "api.decoding": "Sunucu yanıtı işlenemedi.",
        "api.empty_response": "Sunucu boş veri döndürdü.",
        "project.status.complete": "Tamamlandı",
        "project.status.preview_ready": "Ön İzleme Hazır",
        "project.status.hero_ready": "Karakter Hazır",
        "project.status.in_production": "Hazırlanıyor",
        "project.unlock.unlocked": "Açık",
        "project.unlock.preview": "Ön İzleme",
        "project.collection_subtitle": "%@ | %@",
        "style.manga.name": "Manga",
        "style.western.name": "Western Comic",
        "style.cartoon.name": "Cartoon",
        "style.cinematic.name": "Sinematik",
        "style.childrens.name": "Çocuk Kitabı",
        "style.manga.blurb": "Mürekkep odaklı, dramatik kadrajlar ve yüksek kontrastlı tempo.",
        "style.western.blurb": "Vintage pulp enerjisi, güçlü renk ve koleksiyon baskısı hissi.",
        "style.cartoon.blurb": "Stilize karakter oyunculuğu, oyuncu formlar ve temiz ritim.",
        "style.cinematic.blurb": "Prestij kapak dili, dramatik ışık ve rafine anlatı ritmi.",
        "style.childrens.blurb": "Hediye edilebilir sürümler için sıcak hikâye kitabı yumuşaklığı.",
        "style.manga.mood": "Mürekkep Sürümü",
        "style.western.mood": "Koleksiyon Sayısı",
        "style.cartoon.mood": "Animasyon Sürümü",
        "style.cinematic.mood": "Prestij Sürümü",
        "style.childrens.mood": "Hikâye Kitabı",
        "style.manga.signature": "Yüksek kontrastlı hız çizgileri ve mürekkep odaklı dramatik yapı.",
        "style.western.signature": "Vintage pulp renkleri ve güçlü koleksiyon enerjisi.",
        "style.cartoon.signature": "İfade gücü yüksek formlar ve temiz animasyon ritmi.",
        "style.cinematic.signature": "Prestij kadrajlar, dramatik ışık ve premium tempo.",
        "style.childrens.signature": "Hediye edilebilir sürümler için sıcak hikâye kitabı yumuşaklığı.",
        "style.manga.cover_title": "Manga",
        "style.western.cover_title": "Western",
        "style.cartoon.cover_title": "Karikatür",
        "style.cinematic.cover_title": "Sinema",
        "style.childrens.cover_title": "Masal",
        "style.manga.cover_subtitle": "Mürekkep dramı",
        "style.western.cover_subtitle": "Koleksiyon pulp",
        "style.cartoon.cover_subtitle": "Temiz formlar",
        "style.cinematic.cover_subtitle": "Prestij ritmi",
        "style.childrens.cover_subtitle": "Sıcak hatıra",
        "style.manga.cover_eyebrow": "Mürekkep",
        "style.western.cover_eyebrow": "Sayı",
        "style.cartoon.cover_eyebrow": "Sürüm",
        "style.cinematic.cover_eyebrow": "Prestij",
        "style.childrens.cover_eyebrow": "Hikâye",
        "step.pending": "Bekliyor",
        "step.active": "Sürüyor",
        "step.completed": "Tamamlandı",
        "step.failed": "Başarısız",
        "hero_status.queued": "Sırada",
        "hero_status.running": "Çalışıyor",
        "hero_status.succeeded": "Tamamlandı",
        "hero_status.failed": "Başarısız"
    ]
}

extension Error {
    var userFacingMessage: String {
        if let apiError = self as? APIError {
            return apiError.userMessage
        }
        return localizedDescription
    }
}
